# Generated by Django 3.2.7 on 2021-10-10 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='chestpa',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='cov6',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='emephon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='heart',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='phon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appt',
            name='appdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
