# Generated by Django 3.2.7 on 2021-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211010_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
