# Generated by Django 3.2.7 on 2021-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_appt_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='covnow',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appt',
            name='test',
            field=models.BooleanField(null=True),
        ),
    ]
