# Generated by Django 3.2.7 on 2021-11-01 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211028_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='appdatetime',
        ),
        migrations.RemoveField(
            model_name='appt',
            name='test',
        ),
        migrations.AddField(
            model_name='appt',
            name='appconfirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='appdate',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appt',
            name='apprequest',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='result',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='tested',
            field=models.BooleanField(null=True),
        ),
    ]
