# Generated by Django 3.2.7 on 2021-11-01 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211101_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='apptime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appt',
            name='appdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
